repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/jsh9/markdown-toc-creator
    rev: 0.0.8
    hooks:
      - id: markdown-toc-creator