[tool.poetry]
name = "dev"
version = "0.1.0"
description = ""
authors = ["Luis Salamo <lsalamo@gmail.com>"]
readme = "README.md"
packages = [{include = "dev/*"}]

[tool.poetry.dependencies]
python = "^3.7"